
#!/usr/bin/nft -f

flush ruleset

table inet firewall {

```
chain input {
    type filter hook input priority filter; policy drop;

    iifname "lo" accept

    ct state invalid counter drop
    ct state established,related accept

    jump whitelist
    jump logging
}

chain output {
    type filter hook output priority filter; policy accept;
}

chain forward {
    type filter hook forward priority filter; policy drop;
}

chain whitelist {
    ip saddr 192.168.15.39 tcp dport 80 counter accept
    ip saddr 192.168.15.39 tcp dport 2409 counter accept
}

chain logging {
    counter log prefix "NFT INPUT DROP: " drop
}

chain diagnostics {
}
```

}
